language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: never # TODO change to always

branches:
  except:
    - /^gh-pages.*$/

install:
  - travis_retry pip install --upgrade pip
  - pip -V
  - travis_retry pip install --upgrade -r requirements.txt
  - travis_retry pip install --upgrade -e .

script:
  - ./scripts/pep8check.sh
  - ./scripts/coverage.sh
  # TODO add more lines here to be executed in the test stage e.g. pyinstaller etc.

jobs:
  include:
    - os: linux
    - stage: release
      node_js: lts/*
      before_install:
        - export TRAVIS_NODE_VERSION="lts/*"
      install:
        # TODO: install / update python + modules for deployment using twine
        - rm -rf ~/.nvm
        - git clone https://github.com/creationix/nvm.git ~/.nvm
        - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
        - source ~/.nvm/nvm.sh
        - nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
        - npm prune && npm i
      script:
        - npx semantic-release
