<<<<<<< HEAD
title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
=======
theme: jekyll-theme-minimal
>>>>>>> fcde9a2fbeda4cab411395b1c5eaad3f07580d8a
